### ISSUE TITLE
expected indentiefier

### ISSUE THREAD

**Issue by riksnelders** [lajosbencz/vue-wamp#10]
occurs in 

`
function _log(...args) {
  if (_debug) {
    console.debug(...args);
  }
}`

Vue.use(VueWamp, {
    // debug: true,
    url: 'ws://iot.something.nl:9030/ws',
    realm: 'asd',
    onopen: function(session, details) {
        console.log('WAMP connected', session, details);
    },
    onclose: function(reason, details) {
        console.log('WAMP closed: ' + reason, details);
    }
})

on IE (wich i need error less, else not able to use on Fully Kiosk)

**Comment by lajosbencz** [comment]
I think this is a babel related issue, namely it doesn't transpile the ES6 ellipses argument expander to proper ES5 code.

I've refactored it in v1.5.1, that error should go away now.

**Comment by lajosbencz** [comment]
Refactor the build process to generate code for IE>=11.
Should be fixed since the v2.0.0 release.
