### ISSUE TITLE
Subscribe to connection events

### ISSUE THREAD

**Issue by ruudboon** [lajosbencz/vue-wamp#13]
Currently you can only register to the connection events from the configuration.
Would it be possible to add something like this

```
mounted() {
        this.$wamp.onconnect(function(session, details) {
             console.log('WAMP connected', session, details);
        });
    }
```

**Comment by lajosbencz** [comment]
It is now, added it in v2.0.0.

[https://github.com/lajosbencz/vue-wamp#events](https://github.com/lajosbencz/vue-wamp#events)
