### ISSUE TITLE
Timeout event

### ISSUE THREAD

**Issue by liho26** [lajosbencz/vue-wamp#14]
Hi.
I have few subscriptions for different channels under one WAMP connection. From time to time some channels stop providing  data. Hot to check it? Does component have timeout for subscription or some similar model?

For example, if subscription doesn't get any info for 1 min, unsubscribe automatically. Or how I can check if data received or not?

Thank you.

**Comment by lajosbencz** [comment]
This is a simple wrapper to use WAMP in Vue components, i don't think it's the responsibility of this package to do application logic.

You should write a Vue mixin to implement such.
