### ISSUE TITLE
vue-camp update

### ISSUE THREAD

**Issue by liho26** [lajosbencz/vue-wamp#16]
@lajosbencz Hi. I try to use due-wamp with Electron. When app starts I get autobahn error. After some investigation I realised, that this is autobahn's bug. Full description you can found here:

https://github.com/crossbario/autobahn-js/issues/356

Is it possible ask you rebuild due-wamp with new version of autobahn?

**Comment by RBukharov** [comment]
Hi @lajosbencz, liho26, I guess now it's too early to rebuild it: https://github.com/crossbario/autobahn-js/issues/356#issuecomment-407313513

**Comment by RBukharov** [comment]
I suppose, it's time now: https://github.com/crossbario/autobahn-js-browser/releases/tag/v18.10.1
That bug was fixed here: https://github.com/crossbario/autobahn-js/pull/370

**Comment by lajosbencz** [comment]
Thanks for the heads up guys, i've ignored this repo for a while now.
I will do a rewrite of it in the following few days.

**Comment by lajosbencz** [comment]
Update to ```"vue-wamp": "^2.0"```!
