### ISSUE TITLE
Auto unsubscribe with an unsubscribed channel: subscription not active – "beforeDestroy hook"

### ISSUE THREAD

**Issue by zzdever** [lajosbencz/vue-wamp#17]
If a channel is unsubscribed intentionally, when the vue component is destroyed, vue-wamp still unsubsribes that channel, thus cause error: subscription not active – "beforeDestroy hook".

**Comment by lajosbencz** [comment]
Should be fixed now, but only if you call ```$wamp.unregister(registration)``` instead of ```registration.unregister()``` (and unsubscribe respectively).

**Comment by zzdever** [comment]
@lajosbencz 

got error with 2.0.5:
>  ERROR  Failed to compile with 4 errors                                                                                                                                    
> These relative modules were not found:
> * ./_descriptors in ./node_modules/vue-wamp/dist/vue-wamp.js
> * ./_export in ./node_modules/vue-wamp/dist/vue-wamp.js
> * ./_object-assign in ./node_modules/vue-wamp/dist/vue-wamp.js
> * ./_object-dp in ./node_modules/vue-wamp/dist/vue-wamp.js                                                                                                                           

Any idea?

**Comment by lajosbencz** [comment]
Temporary solution described here: #20
