### ISSUE TITLE
Error on installing 2.0.5

### ISSUE THREAD

**Issue by asalisaf** [lajosbencz/vue-wamp#19]
Hello
I get these errors while compiling with Webpack:

 ERROR  Failed to compile with 4 errors       

These relative modules were not found:

* ./_descriptors in ./node_modules/vue-wamp/dist/vue-wamp.js
* ./_export in ./node_modules/vue-wamp/dist/vue-wamp.js
* ./_object-assign in ./node_modules/vue-wamp/dist/vue-wamp.js
* ./_object-dp in ./node_modules/vue-wamp/dist/vue-wamp.js

Any help would be appreciated

**Comment by lajosbencz** [comment]
Hello,

I'm having some trouble properly bundling the plugin.
Currently, rollup is being used to generate a browser, commonjs and umd package, but when transpiling to the browser build, babel-polyfill causes this error.

Temporary solution here: #20

**Comment by asalisaf** [comment]
Thank a lot

**Comment by TheDuckman** [comment]
Hey there,

same problem here. the difference is I'm using `yarn` to manage the packages, not `npm`. I've tried the temporary solution you mentioned (i.e. adding `resolve('node_modules/vue-wamp')` to the `webpack.base.conf.js` file) but that didn't work.

Runing `yarn dev` gives me this:

ERROR  Failed to compile with 4 errors

These relative modules were not found:

* ./_export in ./~/vue-wamp/dist/vue-wamp.js
* ./_object-assign in ./~/vue-wamp/dist/vue-wamp.js
* ./_object-dp in ./~/vue-wamp/dist/vue-wamp.js
* ./_descriptors in ./~/vue-wamp/dist/vue-wamp.js
> Listening at http://localhost:8080

Any other suggestions?

Thanks in advance!

**Comment by asalisaf** [comment]
Hey
use:
 ```
import VueWamp from 'vue-wamp/dist/vue-wamp.esm'
``` 
instead of: 
```
import VueWamp from 'vue-wamp'
```

**Comment by TheDuckman** [comment]
@asalisaf thank you so much! Worked like a charm :D

**Comment by byrgazov** [comment]
```js
// webpack.config.js
// ...
	resolve: {
		extensions: ['.vue', '.ts', '.js'],
		alias: {
			'vue-wamp': 'vue-wamp/dist/vue-wamp.esm.js',
		}
	},
//...
```
