### ISSUE TITLE
[TODO] Fix bundling

### ISSUE THREAD

**Issue by lajosbencz** [lajosbencz/vue-wamp#20]
When installing through npm, the default browser build gets imported.

Resulting error:

```
./_descriptors in ./node_modules/vue-wamp/dist/vue-wamp.js
./_export in ./node_modules/vue-wamp/dist/vue-wamp.js
./_object-assign in ./node_modules/vue-wamp/dist/vue-wamp.js
./_object-dp in ./node_modules/vue-wamp/dist/vue-wamp.js
```

Solution:
Properly configure rollup

**Comment by lajosbencz** [comment]
For now, the solution for me is to include the ```node_modules/vue-wamp``` folder in the webpack babel configuration:

```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          // include vue-wamp for transpilation:
          resolve('node_modules/vue-wamp'),
        ]
      },
```

**Comment by awulkan** [comment]
> For now, the solution for me is to include the `node_modules/vue-wamp` folder in the webpack babel configuration:
> 
> ```js
>       {
>         test: /\.js$/,
>         loader: 'babel-loader',
>         include: [
>           resolve('src'),
>           resolve('test'),
>           // include vue-wamp for transpilation:
>           resolve('node_modules/vue-wamp'),
>         ]
>       },
> ```

@lajosbencz Where exactly did you add that? If I understand it correctly you configure Webpack stuff through the vue.config.js file. Do you have an example with all the code necessary for me to implement it?

Thanks.

**Comment by asalisaf** [comment]
Hey @awulkan 
There is bundling issue as @lajosbencz mentioned and should be fixed.
Permanently you can use one of these solutions:

For ES6 or Typescript:

```import VueWamp from 'vue-wamp/dist/vue-wamp.esm'```

For CommonJS:

```VueWamp = require( 'vue-wamp/dist/vue-wamp.cjs')```

**Comment by TheDuckman** [comment]
> import VueWamp from 'vue-wamp/dist/vue-wamp.esm'

Worked for me

**Comment by lajosbencz** [comment]
Since v3.x, no bundling is provided. It is up to the consumer to transpile the code.
