### ISSUE TITLE
How to receive event to show local notification when app closed

### ISSUE THREAD

**Issue by wa05** [lajosbencz/vue-wamp#22]
Any idea about this..

I'm receiving the event in a Quasar/Córdova app and showing the notification when I received an event from VueWamp..

But I can't with the app closed.. I'll try with FCM I read it works different..

**Comment by lajosbencz** [comment]
If you are referring to Progressive Web Applications, then you would have to put your connection initialization and subscription in your ```service-worker.js```.

But since that's a different environment, you might be better off using ```autobahnjs``` directly, instead of this wrapper plugin.

**Comment by wa05** [comment]
Thanks for your answer, I updated my question..
