### ISSUE TITLE
How to handle reconnect

### ISSUE THREAD

**Issue by flyingfeet** [lajosbencz/vue-wamp#3]
Hey,

I have a problem to subscribe to a topic after the server has restarted (local dev). The reconnection to the server works, but I do not get any events after restart.

```
<template>
    <div>
        <p>Connected: {{ $wampIsConnected }}</p>
    </div>
</template>
<script>
export default {
    wamp: {
        subscribe: {
            'some-topic'(args, kwArgs, details) {
                console.log(args[0])
            }
        }
    }
}
</script>
```
How can I trigger to re-subscribe to the topic?

Thanks for your advice :)

**Comment by lajosbencz** [comment]
Hmmm... that's an oversight by me, give me a few hours and ill try to push out a fix for it!
Thx for the input!

**Comment by flyingfeet** [comment]
Hey, any progress/update? :)

**Comment by lajosbencz** [comment]
Sorry for getting back to you so late, i've pushed a new version which now supports automatic re-subscribe/register
