### ISSUE TITLE
Vuex problem

### ISSUE THREAD

**Issue by lethak** [lajosbencz/vue-wamp#4]
Hi,
Currently testing your wrapper, so far so good, but I noticed a problem regarding the store (Vuex) in Vue-debug (chrome).

In Vuex, Your store state is hijacking my already existing store (used by vue-router and some custom code)

Do you have any idea on this ?

**Comment by lajosbencz** [comment]
Haven't tested that properly, thanks for the report

**Comment by lajosbencz** [comment]
I used vuex to make isOpen, isConnected and isRetrying variables reactive.
They are now deprecated until a better solution, status is still available via methods.
