### ISSUE TITLE
Write onopen and onclose wrappers

### ISSUE THREAD

**Issue by Yamakaky** [lajosbencz/vue-wamp#8]
It would replace https://github.com/lajosbencz/vue-wamp/blob/master/lib/vue-wamp.js#L78-L95 with better results. Potential fix for https://github.com/lajosbencz/vue-wamp/issues/3?

**Comment by lajosbencz** [comment]
Could you please elaborate on the purpose of this modification? I don't see how it would advance the lib

**Comment by Yamakaky** [comment]
Hum, Can't remember what I meant ^^
