### ISSUE TITLE
Use vue-wamp with typescript

### ISSUE THREAD

**Issue by W2K** [lajosbencz/vue-wamp#9]
Is there any typing for Typescript? I was looking through but I could not find it

**Comment by lajosbencz** [comment]
Sorry, i'm not familiar with TypeScript.
But AFAIK, it should be compatible through imports (transpiler should handle it?).

I only skimmed it, but this may be useful to you:
https://github.com/Microsoft/TypeScript/issues/2242

**Comment by lajosbencz** [comment]
Typings are now provided since v3.x
